## GPU VALIDATION

In [1]:
#load rapids data science stack
import cudf
import cuml
import cupy as cp

print("cuDF:", cudf.__version__)
print("cuML:", cuml.__version__)
print("CuPy:", cp.__version__)

cuDF: 26.06.01
cuML: 26.06.00
CuPy: 14.2.0

In [2]:
#confirm device
x = cp.arange(10_000_000, dtype=cp.float32)

print("Device:", x.device)
print("Mean:", x.mean())

Device: <CUDA Device 0>
Mean: 4.9999995e+06

In [3]:
#test df
n = 1_000_000

df_gpu = cudf.DataFrame({
    "x": cp.random.random(n),
    "y": cp.random.random(n)
})

df_gpu.head()

          x         y
0  0.519757  0.748146
1  0.352767  0.255619
2  0.588422  0.291885
3  0.781371  0.602488
4  0.629100  0.055230

In [4]:
df_gpu.describe()

                  x               y
count  1.000000e+06  1000000.000000
mean   5.000962e-01        0.500181
std    2.887301e-01        0.288631
min    7.677044e-07        0.000001
25%    2.495596e-01        0.250392
50%    5.001930e-01        0.500360
75%    7.501796e-01        0.750477
max    9.999999e-01        1.000000

In [5]:
#basic operation test
from cuml.cluster import KMeans

X = cp.random.random((1_000_000, 8))

model = KMeans(
    n_clusters=5,
    random_state=42
)

labels = model.fit_predict(X)

print(labels[:20])

[2 0 0 2 4 1 3 3 0 0 3 3 2 4 3 0 1 0 1 4]