## GPU VALIDATION

In [1]:
import cudf
import cuml
import cupy as cp

print("cuDF:", cudf.__version__)
print("cuML:", cuml.__version__)
print("CuPy:", cp.__version__)

cuDF: 26.06.01
cuML: 26.06.00
CuPy: 14.2.0

In [2]:
x = cp.arange(10_000_000, dtype=cp.float32)

print("Device:", x.device)
print("Mean:", x.mean())

Device: <CUDA Device 0>
Mean: 4.9999995e+06

In [3]:
n = 1_000_000

df_gpu = cudf.DataFrame({
    "x": cp.random.random(n),
    "y": cp.random.random(n)
})

df_gpu.head()

          x         y
0  0.343945  0.654129
1  0.331001  0.231523
2  0.695529  0.449665
3  0.801070  0.547138
4  0.054365  0.914677

In [4]:
df_gpu.describe()

                  x               y
count  1.000000e+06  1000000.000000
mean   5.001883e-01        0.499868
std    2.886734e-01        0.288583
min    3.642990e-07        0.000002
25%    2.504606e-01        0.249872
50%    5.003134e-01        0.499615
75%    7.500457e-01        0.749611
max    1.000000e+00        0.999999

In [5]:
from cuml.cluster import KMeans

X = cp.random.random((1_000_000, 8))

model = KMeans(
    n_clusters=5,
    random_state=42
)

labels = model.fit_predict(X)

print(labels[:20])

[0 0 2 1 3 3 1 2 4 3 1 3 0 0 2 1 0 4 2 0]