## Dataset Prep for Benchmark Test

In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path.home() / "datasets" / "nyc-taxi" / "2025" / "yellow_tripdata_2025-01.parquet"

print(DATA_PATH)
print("Exists:", DATA_PATH.exists())
print("File size (MB):", DATA_PATH.stat().st_size / 1024**2)

/home/dmdgxs/datasets/nyc-taxi/2025/yellow_tripdata_2025-01.parquet
Exists: True
File size (MB): 56.41769218444824

In [2]:
df = pd.read_parquet(DATA_PATH)

In [3]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Shape:", df.shape)

Rows: 3475226
Columns: 20
Shape: (3475226, 20)

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [5]:
df.columns.tolist()

['VendorID',
 'tpep_pickup_datetime',
 'tpep_dropoff_datetime',
 'passenger_count',
 'trip_distance',
 'RatecodeID',
 'store_and_fwd_flag',
 'PULocationID',
 'DOLocationID',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount',
 'congestion_surcharge',
 'Airport_fee',
 'cbd_congestion_fee']

In [6]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [7]:
memory_mb = df.memory_usage(deep=True).sum() / 1024**2
print(f"In-memory pandas size: {memory_mb:.2f} MB")

In-memory pandas size: 493.47 MB

In [8]:
missing = df.isna().sum().sort_values(ascending=False)

missing[missing > 0]

Airport_fee             540149
passenger_count         540149
congestion_surcharge    540149
RatecodeID              540149
store_and_fwd_flag      540149
dtype: int64

In [9]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3.475226e+06,3475226,3475226,2.935077e+06,3.475226e+06,2.935077e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,2.935077e+06,2.935077e+06,3.475226e+06
mean,1.785428e+00,2025-01-17 11:02:55.910964,2025-01-17 11:17:56.997901,1.297859e+00,5.855126e+00,2.482535e+00,1.651916e+02,1.641252e+02,1.036623e+00,1.708180e+01,1.317737e+00,4.780991e-01,2.959813e+00,4.493081e-01,9.547946e-01,2.561129e+01,2.225237e+00,1.239111e-01,4.834093e-01
min,1.000000e+00,2024-12-31 20:47:55,2024-12-18 07:52:40,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-9.000000e+02,-7.500000e+00,-5.000000e-01,-8.600000e+01,-1.269400e+02,-1.000000e+00,-9.010000e+02,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-01-10 07:59:01,2025-01-10 08:15:29.500000,1.000000e+00,9.800000e-01,1.000000e+00,1.320000e+02,1.130000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.520000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-01-17 15:41:33,2025-01-17 15:59:34,1.000000e+00,1.670000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.211000e+01,0.000000e+00,5.000000e-01,2.450000e+00,0.000000e+00,1.000000e+00,1.995000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-01-24 19:34:06,2025-01-24 19:48:31,1.000000e+00,3.100000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,1.950000e+01,2.500000e+00,5.000000e-01,3.930000e+00,0.000000e+00,1.000000e+00,2.778000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-02-01 00:00:44,2025-02-01 23:44:11,9.000000e+00,2.764236e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,8.633721e+05,1.500000e+01,1.050000e+01,4.000000e+02,1.709400e+02,1.000000e+00,8.633804e+05,2.500000e+00,6.750000e+00,7.500000e-01
std,4.263282e-01,NaN,NaN,7.507503e-01,5.646016e+02,1.163277e+01,6.452948e+01,6.940169e+01,7.013334e-01,4.634729e+02,1.861509e+00,1.374623e-01,3.779681e+00,2.002582e+00,2.781938e-01,4.636585e+02,9.039932e-01,4.725090e-01,3.619307e-01

In [10]:
df[
    [
        "trip_distance",
        "fare_amount",
        "tip_amount",
        "total_amount"
    ]
].describe()

       trip_distance   fare_amount    tip_amount  total_amount
count   3.475226e+06  3.475226e+06  3.475226e+06  3.475226e+06
mean    5.855126e+00  1.708180e+01  2.959813e+00  2.561129e+01
std     5.646016e+02  4.634729e+02  3.779681e+00  4.636585e+02
min     0.000000e+00 -9.000000e+02 -8.600000e+01 -9.010000e+02
25%     9.800000e-01  8.600000e+00  0.000000e+00  1.520000e+01
50%     1.670000e+00  1.211000e+01  2.450000e+00  1.995000e+01
75%     3.100000e+00  1.950000e+01  3.930000e+00  2.778000e+01
max     2.764236e+05  8.633721e+05  4.000000e+02  8.633804e+05

In [11]:
print(df["tpep_pickup_datetime"].min())
print(df["tpep_pickup_datetime"].max())

2024-12-31 20:47:55
2025-02-01 00:00:44

In [12]:
print("Pickup zones:", df["PULocationID"].nunique())
print("Dropoff zones:", df["DOLocationID"].nunique())

Pickup zones: 261
Dropoff zones: 260

In [13]:
missing_cols = [
    "Airport_fee",
    "passenger_count",
    "congestion_surcharge",
    "RatecodeID",
    "store_and_fwd_flag"
]

df[missing_cols].isna().all(axis=1).sum()

np.int64(540149)

In [14]:
df[missing_cols].isna().any(axis=1).sum()

np.int64(540149)

In [15]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [16]:
df[
    [
        "trip_distance",
        "fare_amount",
        "tip_amount",
        "total_amount",
        "passenger_count"
    ]
].describe()

,trip_distance,fare_amount,tip_amount,total_amount,passenger_count
count,3.475226e+06,3.475226e+06,3.475226e+06,3.475226e+06,2.935077e+06
mean,5.855126e+00,1.708180e+01,2.959813e+00,2.561129e+01,1.297859e+00
std,5.646016e+02,4.634729e+02,3.779681e+00,4.636585e+02,7.507503e-01
min,0.000000e+00,-9.000000e+02,-8.600000e+01,-9.010000e+02,0.000000e+00
25%,9.800000e-01,8.600000e+00,0.000000e+00,1.520000e+01,1.000000e+00
50%,1.670000e+00,1.211000e+01,2.450000e+00,1.995000e+01,1.000000e+00
75%,3.100000e+00,1.950000e+01,3.930000e+00,2.778000e+01,1.000000e+00
max,2.764236e+05,8.633721e+05,4.000000e+02,8.633804e+05,9.000000e+00

In [17]:
print("Pickup:", df["tpep_pickup_datetime"].min(), "to", df["tpep_pickup_datetime"].max())
print("Dropoff:", df["tpep_dropoff_datetime"].min(), "to", df["tpep_dropoff_datetime"].max())

Pickup: 2024-12-31 20:47:55 to 2025-02-01 00:00:44
Dropoff: 2024-12-18 07:52:40 to 2025-02-01 23:44:11

In [18]:
jan_start = pd.Timestamp("2025-01-01")
feb_start = pd.Timestamp("2025-02-01")

print(
    "Pickup outside January:",
    ((df["tpep_pickup_datetime"] < jan_start) |
     (df["tpep_pickup_datetime"] >= feb_start)).sum()
)

print(
    "Dropoff outside January:",
    ((df["tpep_dropoff_datetime"] < jan_start) |
     (df["tpep_dropoff_datetime"] >= feb_start)).sum()
)

print(
    "Dropoff before pickup:",
    (df["tpep_dropoff_datetime"] < df["tpep_pickup_datetime"]).sum()
)

Pickup outside January: 22
Dropoff outside January: 1811
Dropoff before pickup: 124

In [19]:
duration_minutes = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

duration_minutes.describe()

count    3.475226e+06
mean     1.501812e+01
std      3.871358e+01
min     -5.147232e+04
25%      7.283333e+00
50%      1.170000e+01
75%      1.833333e+01
max      5.626317e+03
dtype: float64

In [20]:
print("Negative durations:", (duration_minutes < 0).sum())
print("Over 24 hours:", (duration_minutes > 1440).sum())

Negative durations: 124
Over 24 hours: 20

In [21]:
bad_duration = df[
    df["tpep_dropoff_datetime"] < df["tpep_pickup_datetime"]
][
    [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "trip_distance",
        "fare_amount",
        "total_amount",
        "PULocationID",
        "DOLocationID"
    ]
]

bad_duration.head(20)

,tpep_pickup_datetime,tpep_dropoff_datetime,trip_distance,fare_amount,total_amount,PULocationID,DOLocationID
99620,2025-01-02 12:26:00,2025-01-02 11:29:58,9.00,45.50,46.00,88,210
459885,2025-01-06 16:00:00,2025-01-06 15:05:30,3.80,24.50,25.00,208,254
1315880,2025-01-15 15:00:00,2025-01-15 14:42:48,1.00,18.50,19.00,107,4
2029534,2025-01-23 01:44:59,2024-12-18 07:52:40,3.10,21.90,30.40,162,238
2058555,2025-01-23 12:30:00,2025-01-23 11:44:59,3.90,27.50,28.00,236,116
2660983,2025-01-29 14:00:00,2025-01-29 13:30:15,1.50,19.50,20.00,72,222
2945475,2025-01-01 10:01:27,2025-01-01 10:01:00,19.19,2.90,68.77,169,35
2945514,2025-01-01 10:01:53,2025-01-01 10:01:33,12.17,1.45,35.87,41,121
2951588,2025-01-02 08:01:41,2025-01-02 08:01:16,14.89,2.90,39.11,28,244
2952145,2025-01-02 11:01:37,2025-01-02 11:01:29,12.71,2.90,34.86,197,74
2952449,2025-01-02 13:01:48,2025-01-02 13:01:35,0.55,2.90,16.00,232,232
2952511,2025-01-02 13:01:55,2025-01-02 13:01:34,5.20,2.90,16.00,213,252
2955341,2025-01-03 11:01:41,2025-01-03 11:01:25,1.72,2.90,16.00,229,263
2955512,2025-01-03 12:01:50,2025-01-03 12:01:41,2.79,2.90,17.24,69,41
2956049,2025-01-03 15:01:39,2025-01-03 15:01:13,6.60,2.90,22.62,233,82
2963170,2025-01-05 02:01:50,2025-01-05 02:01:09,10.97,2.90,35.38,203,72
2967814,2025-01-06 11:01:53,2025-01-06 11:01:23,20.80,2.90,68.43,25,117
2968130,2025-01-06 13:01:38,2025-01-06 13:01:11,2.16,2.90,16.00,197,216
2968292,2025-01-06 14:01:46,2025-01-06 14:01:36,3.86,2.90,18.75,197,10
2968600,2025-01-06 16:01:55,2025-01-06 16:01:07,3.82,2.90,24.09,91,21

In [22]:
long_trips = df[
    duration_minutes > 1440
][
    [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "trip_distance",
        "fare_amount",
        "total_amount"
    ]
]

long_trips.sort_values(
    "tpep_pickup_datetime"
).head(20)

,tpep_pickup_datetime,tpep_dropoff_datetime,trip_distance,fare_amount,total_amount
55016,2025-01-01 17:49:26,2025-01-03 11:15:10,0.66,7.20,11.20
85681,2025-01-02 09:40:31,2025-01-04 09:37:01,0.00,3.00,4.50
414374,2025-01-06 02:12:11,2025-01-09 13:54:19,91.51,336.90,339.40
450646,2025-01-06 15:27:49,2025-01-07 16:59:37,26.36,70.00,71.50
456243,2025-01-06 16:11:55,2025-01-08 07:35:19,6.93,28.20,38.95
556772,2025-01-07 18:07:33,2025-01-09 16:12:05,1.86,47.80,51.80
898201,2025-01-11 08:04:00,2025-01-13 16:49:28,0.04,70.00,76.50
1404958,2025-01-16 12:23:14,2025-01-17 14:41:56,255.33,2450.90,2506.71
1536147,2025-01-17 16:45:49,2025-01-19 16:40:59,1.98,12.80,20.05
1832541,2025-01-21 05:22:58,2025-01-22 05:49:40,0.44,35.20,37.70
1832540,2025-01-21 05:22:58,2025-01-22 05:49:40,0.44,-35.20,-37.70
1858816,2025-01-21 12:23:41,2025-01-25 10:10:00,6.55,-28.20,-36.45
1858817,2025-01-21 12:23:41,2025-01-25 10:10:00,6.55,28.20,36.45
2029659,2025-01-23 01:11:23,2025-01-24 17:30:28,2.93,13.50,19.25
2147536,2025-01-24 07:07:21,2025-01-26 10:09:44,0.00,3.00,4.50
2460536,2025-01-27 11:58:55,2025-01-30 09:42:55,0.00,3.00,4.50
2538084,2025-01-28 10:48:56,2025-01-29 15:08:34,0.00,3.00,4.50
2548395,2025-01-28 12:59:43,2025-01-29 15:05:02,0.46,6.50,11.25
3417048,2025-01-29 21:39:23,2025-01-31 16:48:43,7.52,31.02,35.77
2745903,2025-01-30 11:24:49,2025-01-31 16:31:32,0.00,3.00,4.50

In [26]:
# Remove trips with impossible or implausible durations:
# - negative duration
# - duration greater than 24 hours
duration_minutes = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

df_clean = df[
    (duration_minutes >= 0) &
    (duration_minutes <= 1440)
].copy()

In [27]:
print("Original rows:", len(df))
print("Clean rows:", len(df_clean))
print("Removed rows:", len(df) - len(df_clean))

Original rows: 3475226
Clean rows: 3475082
Removed rows: 144

In [28]:
print(df_clean.shape)

(3475082, 20)

In [29]:
clean_path = Path.home() / "datasets" / "nyc-taxi" / "2025" / "yellow_tripdata_2025-01_clean.parquet"

df_clean.to_parquet(clean_path, index=False)

In [30]:
print(clean_path)
print(f"Cleaned rows: {len(df_clean):,}")

/home/dmdgxs/datasets/nyc-taxi/2025/yellow_tripdata_2025-01_clean.parquet
Cleaned rows: 3,475,082

In [31]:
# reviewing missing values found earlier
missing_cols = [
    "Airport_fee",
    "passenger_count",
    "congestion_surcharge",
    "RatecodeID",
    "store_and_fwd_flag"
]

all_missing = df_clean[missing_cols].isna().all(axis=1).sum()
any_missing = df_clean[missing_cols].isna().any(axis=1).sum()

print("All five missing:", all_missing)
print("Any of five missing:", any_missing)

All five missing: 540030
Any of five missing: 540030

In [33]:
# missing associate with vendor or payment type?
mask_missing = df_clean["passenger_count"].isna()

print(df_clean.loc[mask_missing, "VendorID"].value_counts(dropna=False))
print()
print(df_clean.loc[mask_missing, "payment_type"].value_counts(dropna=False))

VendorID
2    451455
1     88204
6       371
Name: count, dtype: int64

payment_type
0    540030
Name: count, dtype: int64

In [34]:
# allowing considering this is a benchmark project
# payment type 0 = flex fair (if review is necessary)

In [35]:
missing_pct = mask_missing.mean() * 100

print(f"Flex Fare/missing block: {mask_missing.sum():,} rows")
print(f"Percentage of cleaned dataset: {missing_pct:.2f}%")

Flex Fare/missing block: 540,030 rows
Percentage of cleaned dataset: 15.54%

In [36]:
# removing would distort the data set for benchmarking